### ISSUE TITLE
Missing corrupted data

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#105]
Apparently missing route and weight data/corrupted route days in Hilton Head: Feb. 20 and Mar 5.

The data is entered by the Day Captain and for some reason the database is corrupted.   The data and the route schedule disappears.  If the route is refreshed and data re-entered it disappears again.  

Could be associated with the fix to stop the overwrite issue when a Bluffton Tablet was accidentally started as a Hilton Head route and then closed, causing the data to overwrite to zero any prior Hilton Head entries?

**Comment by megandalster** [comment]
Hi Paula,

Sorry for the problem.  To restore all the stops on a blank route, you always can check the box and hit the Refresh button at the bottom of the route.  But this only restores the stops — after that, you need to reenter the weights for each stop.

I just restored the stops for the Feb 20 and March 5 routes.  

Keep me posted if this happens again.  It’s odd that it’s happening on certain days in Hilton Head.  Is there one person who enters the weights for those particular days?  Knowing who is entering the data and how they're doing it could help solve the problem.

**Comment by megandalster** [comment]
This is now fixed. Please review for a couple of weeks and let me know if there are problems.
