### ISSUE TITLE
New Client Data Report

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#39]
See Page A-2.  New report not installed?

**Comment by megandalster** [comment]
Oops, sorry -- look for the dropdown report called "Client Detail"  (not "Recipient Details")

**Comment by secondhelpingsadmin** [comment]
Dates s/b in MM-DD-YYYY format.

**Comment by megandalster** [comment]
okay, done

**Comment by secondhelpingsadmin** [comment]
Dates are in correct format.
