### ISSUE TITLE
Volunteer Input From

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#40]
See Page A-3.  Default Status to 'Active'.  Move License State and Expiration up.  Much prefer old style of drop down calendar at all occurrences.

**Comment by megandalster** [comment]
Done, but left birth date in old form.

**Comment by secondhelpingsadmin** [comment]
Status good, layout looks good.  License Expire date should NOT be d/d calendar, 'cause expire dates are usually 5+ years out into the future.; use same format as Birth Date.  I prefer the old style calendar display as in current Reports request screen that is not transparent.

**Comment by megandalster** [comment]
fixed.

**Comment by secondhelpingsadmin** [comment]
License date format good, d/d calendar format restored.
