### ISSUE TITLE
Client Detail Report dates

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#43]
Date s/b in MM-DD-YYYY format.

Recipient | LCFB | Charity Trkr | Survey Date | Visit Date | Food Safe Date | # Served
-- | -- | -- | -- | -- | -- | --
Agape Family Life Ctr (Blf) | yes | yes | 17-04-30 | 17-06-30 | 17-09-30 | 125

**Comment by megandalster** [comment]
try this one again... should be fixed now.

**Comment by secondhelpingsadmin** [comment]
Dates are in correct mm-dd-yyyy format.
