### ISSUE TITLE
Code text displays where shouldn't.

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#45]
This piece of code, '); printWin.document.close(); }, displays on Volunteer, Donors and Recipients, and Reports header pages.

P. S.  github's bold text function doesn't work.

**Comment by megandalster** [comment]
fixed.  Note that the print list button now works, while it didn't before.

**Comment by secondhelpingsadmin** [comment]
Closed 12/23/2017.
