### ISSUE TITLE
Breakdowns by Food Type Report

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#49]
12/29/17.  Pre-existing problem, not related to new enhancements.  Appears to be bad data on two separate days for Beaufort routes that make this report unfilled for periods that include the days 5/8/17 or 8/21/17.  All other bases and periods appear good.
[Breakdowns by Food Type Reports.pdf](https://github.com/megandalster/sh-homeplate/files/1593558/Breakdowns.by.Food.Type.Reports.pdf)

**Comment by megandalster** [comment]
I will look into the database and try to clean out the problem.  If you could provide a narrower range of dates, that would help my search.  Thanks.

**Comment by megandalster** [comment]
related to issue #58?  I'll look at both together.

**Comment by secondhelpingsadmin** [comment]
Same as #58, which has specific dates.
