### ISSUE TITLE
Detail Report

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#52]
1.  Initiate report from donors and recipients page
2.  Make text changes as noted.
3.  Align 'Total' column.
4.  Implem
[Detail Report.pdf](https://github.com/megandalster/sh-homeplate/files/1620294/Detail.Report.pdf)
ent 'Print List' functionality.

**Comment by megandalster** [comment]
This is done but I left it on the reports page.  See my comment on issue # 51

**Comment by secondhelpingsadmin** [comment]
All good except item 1; save for later.
