### ISSUE TITLE
Route Information Form

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#53]
1.  Add 'Difference' where most convenient.
2.  Make text changes as noted.
[Route Information Form.pdf](https://github.com/megandalster/sh-homeplate/files/1620323/Route.Information.Form.pdf)

**Comment by megandalster** [comment]
This is fixed now.

**Comment by secondhelpingsadmin** [comment]
New 'Difference' field and calculation looks good.
[Delete] button and following text should say 'Refresh'.

**Comment by megandalster** [comment]
changed button to "Refresh".

**Comment by secondhelpingsadmin** [comment]
Good, tks.
