### ISSUE TITLE
Consolidate Donors, Recipents for Mixed Base Routes

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#54]
1.  Investigate way to have one consolidated donor/recipient record on multiple base routes.
2.  Make text changes as noted.
[Multiple Route Schedules.pdf](https://github.com/megandalster/sh-homeplate/files/1620373/Multiple.Route.Schedules.pdf)

**Comment by megandalster** [comment]
done.  login at npfi.org/homeplate and select a donor or recipient.  The form now shows 3 sets of boxes (days) for pickups/dropoffs.  New routes generated for a given truck will now show all stops, both inside and outside that truck's base -- the stops are determined by the boxes checked for that donor or recipient.

**Comment by secondhelpingsadmin** [comment]
Good.
