### ISSUE TITLE
New Weekly Route Schedule

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#56]
Produce new weekly route schedule modeled on attached.  Allow selection by Base. List pick ups first, then drop offs.  Report begins on Monday of current week.  Search button initiates report.

[Weekly Route Schedule.pdf](https://github.com/megandalster/sh-homeplate/files/1620441/Weekly.Route.Schedule.pdf)

**Comment by megandalster** [comment]
done.  login at npfi.org/homeplate and select Routes to review.

**Comment by secondhelpingsadmin** [comment]
Good.
