### ISSUE TITLE
Last Trip Date incorrect posting

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#63]
Entry appears to default to 12/31/1969, can't be corrected or over-written and 'take'.  Two examples in Hilton Head base.  These examples may have been entered manually, not from tablet upload.

Roll, Bob | 843-342-9192 | rollhhi@yahoo.com | Mon:odd, Tue:odd, Mon:even, Tue:even, | 8432909752 | 99 | 12-31-1969 |  
Ryan, Art | 843-785-5453 | artdryan@gmail.com | Fri:odd, Fri:even, | 8432959053 | 18 | 12-31-1969

**Comment by megandalster** [comment]
This is related to issue #65 and is fixed now.

**Comment by megandalster** [comment]
Okay, try this again... I did not upload the bug fix for #63, #64, and #65 properly to your live version.  Should be okay now.

**Comment by secondhelpingsadmin** [comment]
Date posts correctly as manually entered.
