### ISSUE TITLE
Break Down by Food Type Report #2, Beaufort only

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#66]
Second Helpings Truck Weight Report for base: Beaufort, all counties , all delivery areas, food type breakdowns.
Sunday July 9, 2017
Store | Meat | Deli | Bakery | Grocery | Dairy | Produce | Total
-- | -- | -- | -- | -- | -- | -- | --
BiLo Shell Point (525) | 150 | 0 | 0 | 0 | 0 | 150 | 300
Food | adies | sland | 30 | 15 | 100 | 0 | 130 | 0 | 15 | 130
Food Lion Laurel Bay (1698) | 0 | 150 | 0 | 0 | 0 | 200 | 350
Publix Ladys Island (1463) | 100 | 50 | 250 | 0 | 0 | 150 | 550
Totals | 250 | 200 | 280 | 15 | 100 | 500 | 1460 | 0 | 15

Look at in Reports..... easier to see.  Does not prevent generating a report.  Minor item, low priority.

**Comment by megandalster** [comment]
More junk in the database from July 9.  I'll try to get this out of there, but there are other cases like this scattered around over the last 2 years.  Not sure I can remove them all without doing damage to the good data.

**Comment by megandalster** [comment]
Okay, this one is fixed.

**Comment by secondhelpingsadmin** [comment]
Not critical as long as report generates.  We can live with.
