### ISSUE TITLE
Invalid Data -= Creative Church

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#67]
home | routes | master schedules | volunteers | affiliates | areas | donors and recipients | reports | logout
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's','doriottbydesign@gmail.com','','Judy Wheeleer','','10','18-01-24','','17-02-2' at line 1 Unable to insert into dbClients: Creative Church Food Pantry
Unable to update Creative Church Food Pantry. 
Please report this error to the Program Coordinator.

**Comment by megandalster** [comment]
Not sure what happened here.  The entry looks good now.  Did you type a single quote (') when making changes?

**Comment by secondhelpingsadmin** [comment]
I may have entered a '.  I think I re-entered afresh as new recipient.  Pls determine if there is a 'bad' recipient record hanging around; if 'yes', can weights be xferred?

**Comment by megandalster** [comment]
There's just one recipient record for Creative Church in the database.  So this one's fixed.
