### ISSUE TITLE
Fatal error on route refresh

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#68]
Crew: | Pick-ups -- weights | Drop-offs -- weights
-- | -- | --
Ed GruelBarry FredericksDan ResetaritsKathy KrauseBob Schmidt | Food Lion Kitties Xing (1330)Fatal error: Call to a member function get_total_weight() on boolean in /home/content/62/9326362/html/homeplate/routeForm.inc on line 94

Tried to refresh a route after entering new Recipient: Creative Church.  May be related to prior issue on Creative Church mainatenance.

**Comment by megandalster** [comment]
I cannot replicate this one.  Looks okay now.

**Comment by secondhelpingsadmin** [comment]
OK.
