### ISSUE TITLE
Invalid Volunteer record = Lurtz, Terry M.

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#70]
This Beaufort volunteer has been deleted, but still shows up on search; cannot select to delete.

**Comment by megandalster** [comment]
There was a blank space in Terry's first name "Terry M.", which Homeplate doesn't like.  I fixed this in the database.  Now he shows up as "Terry" and you can edit his profile data, or delete him as needed.

**Comment by secondhelpingsadmin** [comment]
Name fixed (blank space).
