### ISSUE TITLE
Convert Hilton Head volunteer schedules to five-week calendar.

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#82]
Beaufort schedules weeks 1 through 5; HHI schedules weeks Odd-Even.  Convert HHI to same Week 1-5 method as Beaufort.

**Comment by megandalster** [comment]
I will make this change, but a lot of HHI volunteers will need to be recoded for weeks 1-5 instead of odd-even.  Until this happens, the HHI master schedule will show no volunteers.

**Comment by megandalster** [comment]
done.  login at npfi.org/homeplate to review.  The HH schedule is initially blank, as will be any new routes generated.  It will repopulate populate as you reschedule each HH volunteer into the 1-5 week form, one by one.  New routes in the future will gradually reflect this new schedule.

**Comment by secondhelpingsadmin** [comment]
Looks good.
