### ISSUE TITLE
FTP updates unusable version

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#83]
FTP auto-updates to non-3.2 version that does not xfer files.

**Comment by megandalster** [comment]
To prevent this auto-updating, do the following steps on each tablet.
1.  Open **Google Play**.
2.  Tap the **menu** (three horizontal lines) on the top-left.
3.  Tap **Settings**.
4.  Tap **Auto-update apps**.
5.  Select **Do not auto-update apps**. 
This should also be added to the instructions for setting up a new tablet.
