### ISSUE TITLE
Warning msgs

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#87]
Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /home/content/62/9326362/html/homeplate/database/dbVolunteers.php on line 43

Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /home/content/62/9326362/html/homeplate/database/dbVolunteers.php on line 43

Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /home/content/62/9326362/html/homeplate/database/dbVolunteers.php on line 63

Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /home/content/62/9326362/html/homeplate/database/dbVolunteers.php on line 63

**Comment by megandalster** [comment]
fixed.  login at npfi.org/homeplate to confirm.

**Comment by secondhelpingsadmin** [comment]
OK.
