### ISSUE TITLE
AND FTP downloads against tablet lock

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#88]
Tablet 1f5b was 'locked' on 12/10/18.  Upload attempted today used 'unworkable' version of FTP.  I unlocked tablet, uninstalled/installed FTP, did upload/download correctly.  This is only know instance so far of FTP not working on a locked tablet (unless the 'good' FTP 3.2 version also has problems?).  How can I determine version of FTP installed before attempting upload?  Look in Drive? Didn't think to do that before uninstalled/installed; not sure what version was resident on first upload attempt.

**Comment by megandalster** [comment]
To see the version of FTP on the tablet, go to Settings -> Apps and select AndFTP.  The version (3.2) shows up right there.
