### ISSUE TITLE
Fatal error on Route refresh.

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#92]
Crew: | Pick-ups -- weights | Drop-offs -- weights
-- | -- | --
Thomas BlairPete BongiavanniWilliam KrebsMichael McKeown | Fatal error: Call to a member function get_items() on boolean in /home/content/62/9326362/html/homeplate/routeForm.inc on line 88

**Comment by megandalster** [comment]
what was the date and location for this error?

**Comment by secondhelpingsadmin** [comment]
Location was Beaufort, date don't remember.  Can close if can't find, will reopen if re-occurs.
