### ISSUE TITLE
AND FTP 3.2

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#97]
Tablet ID beginning f577.... (I have double checked correct ID in Tablet table).  Weight entry seems normal, WiFi seems normal.  Upload disconnects immediately, no upload activity, then download brings down 42 files (correct number).  No weights appear on server.  Download status screen (yellow bar) does not light on upload, lights repeatedly on download.
Maybe relevant question: when you enter weight as Total Weight (not breakdown), where is the weight recorded on server when uploaded?  Is there a Total bucket as well as by food type?

**Comment by megandalster** [comment]
tablet fixed.  Will deliver to office 4/15
